on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main
      - develop
jobs:
  test:
    name: flutter test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: load fvm_config.json
        uses: kuhnroyal/flutter-fvm-config-action@v1
      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
      - name: setup dependencies
        run: |
          flutter pub get
          flutter pub run build_runner build
          flutter gen-l10n
      - name: run test
        run: flutter test